# Generated by Django 4.2.5 on 2024-03-19 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=75, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Base_Temporary_storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_id', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_create', models.DateField(auto_now_add=True)),
                ('data_dead_line', models.DateField(null=True)),
                ('data_update', models.DateField(auto_now=True)),
                ('about', models.JSONField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='temporary_storage.author')),
            ],
            options={
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('base_temporary_storage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='temporary_storage.base_temporary_storage')),
            ],
            bases=('temporary_storage.base_temporary_storage',),
        ),
        migrations.CreateModel(
            name='Temporary_storage',
            fields=[
                ('base_temporary_storage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='temporary_storage.base_temporary_storage')),
            ],
            bases=('temporary_storage.base_temporary_storage',),
        ),
        migrations.CreateModel(
            name='Undeclared_temporary_storage',
            fields=[
                ('base_temporary_storage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='temporary_storage.base_temporary_storage')),
            ],
            bases=('temporary_storage.base_temporary_storage',),
        ),
        migrations.AddField(
            model_name='base_temporary_storage',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='temporary_storage.executor'),
        ),
        migrations.AddField(
            model_name='base_temporary_storage',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='temporary_storage.tag_post'),
        ),
    ]
