# Generated by Django 4.2.5 on 2024-01-19 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temporary_storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=255)),
                ('price_id', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_create', models.DateField(auto_now_add=True)),
                ('data_dead_line', models.DateField(null=True)),
                ('data_update', models.DateField(auto_now=True)),
                ('about', models.JSONField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='temporary_storage.author')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='temporary_storage.executor')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='temporary_storage.tag_post')),
            ],
            options={
                'ordering': ['-date_create'],
            },
        ),
    ]
