# Generated by Django 4.2.5 on 2023-11-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporary_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag_post',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
